name: Installation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: submodule update
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgdal-dev libspatialindex-dev
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install package
        run: pip install -e .
